application: magento-gae
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /skin
  static_dir: var/skin
# application_readable: true
  expiration: 30d

- url: /js
  static_dir: magento/js
  expiration: 30d

- url: /errors/default/images
  static_dir: magento/errors/default/images
  expiration: 30d

- url: /errors/default/css
  static_dir: magento/errors/default/css
  expiration: 30d

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: 30d

- url: /materialize.php
  script: materialize.php

- url: /cron.php
  script: cron.php

- url: .*
  script: index.php


skip_files:
# Skins are served separately
- ^magento/skin.*
# Useless directories for GAE
- ^magento/var.*
- ^magento/media.*
- ^magento/downloader.*
- ^magento/pkginfo.*
- ^magento/shell.*
- ^magento/lib/flex/.*
# Unused Modules
- ^magento/lib/Zend/Amf.*
- ^magento/lib/Zend/Application.*
- ^magento/lib/Zend/Auth.*
- ^magento/lib/Zend/Barcode.*
- ^magento/lib/Zend/Cloud.*
- ^magento/lib/Zend/CodeGenerator.*
- ^magento/lib/Zend/Dojo.*
- ^magento/lib/Zend/Form.*
- ^magento/lib/Zend/Ldap.*
- ^magento/lib/Zend/InfoCard.*
- ^magento/lib/Zend/Queue.*
- ^magento/lib/Zend/Search.*
- ^magento/lib/Zend/Service.*
- ^magento/lib/Zend/Test.*
- ^magento/lib/Zend/Tool.*
- ^magento/lib/Zend/View.*
# Google Base
- ^magento/lib/Zend/Gdata.*
#Connect And Backup
- ^magento/lib/Mage.*
- ^magento/app/code/core/Mage/Connect.*
- ^magento/app/code/core/Mage/Backup.*
#Google checkout
- ^magento/lib/googlecheckout.*
- ^magento/app/code/core/Mage/GoogleCheckout.*
#MoneyBookers
- ^magento/app/code/community/Phoenix.*
#Mage Compiler
- ^magento/app/code/core/Mage/Compiler.*
#API
- ^magento/app/code/core/Mage/Api.*
- ^magento/app/code/core/Mage/Api2.*
# git
- ^magento/\.git/.*
- ^\.git/.*