application: magento-gae
version: 1
runtime: php
api_version: 1

handlers:
- url: /skin
  static_dir: gae/material_skin
#  application_readable: true
  expiration: 30d

- url: /js
  static_dir: js
  expiration: 30d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 30d

- url: /cron.php
  script: gae/cron.php

- url: .*
  script: gae/index.php


skip_files:
# Skins are served separately
- ^skin.*
# Useless directories for GAE
- ^var.*
- ^media.*
- ^downloader.*
- ^pkginfo.*
- ^shell.*
- ^lib/flex/.*
# Unused Modules
- ^lib/Zend/Amf.*
- ^lib/Zend/Application.*
- ^lib/Zend/Auth.*
- ^lib/Zend/Barcode.*
- ^lib/Zend/Cloud.*
- ^lib/Zend/CodeGenerator.*
- ^lib/Zend/Dojo.*
- ^lib/Zend/Form.*
- ^lib/Zend/Ldap.*
- ^lib/Zend/InfoCard.*
- ^lib/Zend/Queue.*
- ^lib/Zend/Search.*
- ^lib/Zend/Service.*
- ^lib/Zend/Test.*
- ^lib/Zend/Tool.*
- ^lib/Zend/View.*
# Google Base
- ^lib/Zend/Gdata.*
#Connect And Backup
- ^lib/Mage.*
- ^app/code/core/Mage/Connect.*
- ^app/code/core/Mage/Backup.*
#Google checkout
- ^lib/googlecheckout.*
- ^app/code/core/Mage/GoogleCheckout.*
#MoneyBookers
- ^app/code/community/Phoenix.*
#Mage Compiler
- ^app/code/core/Mage/Compiler.*
#API
- ^app/code/core/Mage/Api.*
- ^app/code/core/Mage/Api2.*
- ^\.git/.*
